package com.servify.notificaciones.domain.enumtype;

public enum TipoNotificacion {
    MODERACION_PUBLICACION,
    MODERACION_USUARIO,
    SOLICITUD_COMPATIBLE,
    SOLICITUD_RESPONDIDA,
    SOLICITUD_CANCELADA,
    CONTRAOFERTA_RECIBIDA,
    CONTRAOFERTA_RESUELTA,
    SERVICIO_ASIGNADO,
    SERVICIO_FINALIZACION,
    CALIFICACION_RECIBIDA,
    MENSAJE_CHAT
}
