CREATE TABLE IF NOT EXISTS public.publicacion_zona_cobertura (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    publicacion_id bigint NOT NULL,
    pais character varying(255),
    provincia character varying(255),
    ciudad character varying(255),
    localidad character varying(255),
    calle character varying(255),
    altura character varying(50),
    referencia character varying(255),
    latitud double precision,
    longitud double precision
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'publicacion_zona_cobertura_pkey'
    ) THEN
        ALTER TABLE ONLY public.publicacion_zona_cobertura
            ADD CONSTRAINT publicacion_zona_cobertura_pkey PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_publicacion_zona_publicacion'
    ) THEN
        ALTER TABLE ONLY public.publicacion_zona_cobertura
            ADD CONSTRAINT fk_publicacion_zona_publicacion
            FOREIGN KEY (publicacion_id) REFERENCES public.publicacion_servicio(id) ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_publicacion_zona_publicacion
    ON public.publicacion_zona_cobertura USING btree (publicacion_id);

CREATE INDEX IF NOT EXISTS idx_publicacion_zona_localidad
    ON public.publicacion_zona_cobertura USING btree (ciudad, localidad);

INSERT INTO public.publicacion_zona_cobertura (
    publicacion_id,
    pais,
    provincia,
    ciudad,
    localidad,
    calle,
    altura,
    referencia,
    latitud,
    longitud
)
SELECT
    p.id,
    p.pais,
    p.provincia,
    p.ciudad,
    p.localidad,
    p.calle,
    p.altura,
    p.referencia,
    p.latitud,
    p.longitud
FROM public.publicacion_servicio p
WHERE NOT EXISTS (
    SELECT 1
    FROM public.publicacion_zona_cobertura z
    WHERE z.publicacion_id = p.id
);
